# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
# config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.name = "aws-utils"
    v.memory = 512
    v.cpus = 1
  end

  config.vm.box_check_update = true

  #SSH
  config.ssh.forward_agent = true

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  #Provision scripts
  config.vm.provision "shell", path: "ubuntu-aws-utils.sh"

end
